#Available stages to run in 'automatic' processing:
# For convenience, implicit stages have been made explicit here...
stages:
  - Initialization
  - Setup
  - Privatization Tests 7.3.0
  - Privatization Tests 7.5.0
  - Workshare Tests
  - Finalization

.run_by_main: &run_by_main
  only:
  - devel
  - master
  - merge_requests
  - web

.source_env: &source_env
  variables:
    PATH: "$HOME/GL_$CI_PIPELINE_ID/install_730/bin:$PATH"
    INCLUDE_PATH: "$HOME/GL_$CI_PIPELINE_ID/install_730/include:$INCLUDE_PATH"
    CPATH: "$HOME/GL_$CI_PIPELINE_ID/install_730/include:$CPATH"
    LD_LIBRARY_PATH: "$HOME/GL_$CI_PIPELINE_ID/install_730/lib:$HOME/GL_$CI_PIPELINE_ID/install_730/lib64:$LD_LIBRARY_PATH"

############################
##### EXTRA ACTIONS ########
############################
#these actions should herit from implicit stages ".pre" and ".post"

# pre-actions to cleanup the machine before the run
# this job will be run in ANY pipeline -> ensure to enable all proper tags
# CAUTION : Otherwise tag-specific runners won't allow to run the whole pipeline because
# both .pre and .post cannot be scheduled (thus, why not using user-defined pre and post
# to avoid them to be run systematically ?)
Env Sanitize:
  <<: *run_by_main
  stage: Initialization
  script:
    - mkdir -p $HOME/GL_$CI_PIPELINE_ID/{build_730,build_750,build_730-nogcc}
    - echo "Environment Cleaned !"

# post-actions to cleanup the machine after the run
# The last line may not be necessary as a pipeline start run something like a "git clean" before running
# This implies a probable issue when multiple piplines are run concurrently on the same project :(
# Please read the CAUTION above !
Artifact Deletion:
  <<: *run_by_main
  stage: Finalization
  allow_failure: true
  when: on_success
  script:
    - $HOME/clean_old_pipelines.sh
    - rm -rf $HOME/$CI_PIPELINE_ID/

############################
####### BUILD STAGE ########
############################

Build:
  <<: *run_by_main
  stage: Setup
  script:
  - cd $HOME/GL_$CI_PIPELINE_ID/build_730
  - ${CI_PROJECT_DIR}/configure --prefix=$HOME/GL_$CI_PIPELINE_ID/install_730 --enable-debug --enable-color
  - make -j8

Build 7.5.0 priv:
  <<: *run_by_main
  stage: Setup
  script:
  - cd $HOME/GL_$CI_PIPELINE_ID/build_750
  - ${CI_PROJECT_DIR}/configure --prefix=$HOME/GL_$CI_PIPELINE_ID/install_750 --enable-debug --enable-color --disable-workshare --gcc-version=7.5.0
  - make -j8

Build-nogcc:
  <<: *run_by_main
  stage: Setup
  script:
  - cd $HOME/GL_$CI_PIPELINE_ID/build_730-nogcc
  - ${CI_PROJECT_DIR}/configure --prefix=$HOME/GL_$CI_PIPELINE_ID/install_730-nogcc --enable-debug --enable-color --disable-gcc
  - make -j8

#################################
####### PRIV TESTS 7.3.0 ########
#################################


No-privatization:
  <<: *run_by_main
  stage: Privatization Tests 7.3.0
  script:
  - cd $HOME/GL_$CI_PIPELINE_ID/build_730/BUILD_autopriv
  - EXTLS_VERBOSE=debug make check -C tests/nopriv VERBOSE=1

With-privatization:
  <<: *run_by_main
  stage: Privatization Tests 7.3.0
  script:
  - cd $HOME/GL_$CI_PIPELINE_ID/build_730/BUILD_autopriv
  - EXTLS_VERBOSE=debug make check -C tests/priv VERBOSE=1

Compil Wrappers:
  <<: *run_by_main
  stage: Privatization Tests 7.3.0
  script: 
  - cd $HOME/GL_$CI_PIPELINE_ID/build_730/BUILD_autopriv
  - EXTLS_VERBOSE=debug make check -C tests/wrappers VERBOSE=1

Not supported:
  <<: *run_by_main
  stage: Privatization Tests 7.3.0
  allow_failure: true
  script: 
  - cd $HOME/GL_$CI_PIPELINE_ID/build_730/BUILD_autopriv
  - EXTLS_VERBOSE=debug make check -C tests/unsupported VERBOSE=1

#################################
####### PRIV TESTS 7.5.0 ########
#################################


No-privatization:
  <<: *run_by_main
  stage: Privatization Tests 7.5.0
  script:
  - cd $HOME/GL_$CI_PIPELINE_ID/build_750/BUILD_autopriv
  - EXTLS_VERBOSE=debug make check -C tests/nopriv VERBOSE=1

With-privatization:
  <<: *run_by_main
  stage: Privatization Tests 7.5.0
  script:
  - cd $HOME/GL_$CI_PIPELINE_ID/build_750/BUILD_autopriv
  - EXTLS_VERBOSE=debug make check -C tests/priv VERBOSE=1

Compil Wrappers:
  <<: *run_by_main
  stage: Privatization Tests 7.5.0
  script: 
  - cd $HOME/GL_$CI_PIPELINE_ID/build_750/BUILD_autopriv
  - EXTLS_VERBOSE=debug make check -C tests/wrappers VERBOSE=1

Not supported:
  <<: *run_by_main
  stage: Privatization Tests 7.5.0
  allow_failure: true
  script: 
  - cd $HOME/GL_$CI_PIPELINE_ID/build_750/BUILD_autopriv
  - EXTLS_VERBOSE=debug make check -C tests/unsupported VERBOSE=1


#################################
####### WORKSHARE TESTS  ########
#################################


Simple Tests:
  <<: *run_by_main
  stage: Workshare Tests
  allow_failure: false
  script: 
  - cd $HOME/GL_$CI_PIPELINE_ID/build_730/BUILD_workshare
  - make check -C tests/simple VERBOSE=1
