default:
  before_script:
      # Fix git timestamp mismatch in autotools
      - cd ${CI_PROJECT_DIR} && (find . | xargs touch -r ./configure)



#Available stages to run in 'automatic' processing:
# For convenience, implicit stages have been made explicit here...
stages:
  - Validation
  - Finalization

############################
##### EXTRA ACTIONS ########
############################

# post-actions to cleanup the machine after the run
# The last line may not be necessary as a pipeline start run something like a "git clean" before running
# This implies a probable issue when multiple piplines are run concurrently on the same project :(
# Please read the CAUTION above !
Artifact Deletion:
  stage: Finalization
  allow_failure: true
  when: on_success
  script:
    - $HOME/clean_old_pipelines.sh
    - rm -rf $HOME/GL_$CI_PIPELINE_ID/

############################
####### BUILD STAGE ########
############################

nogcc:
  stage: Validation
  tags:
    - docker
  image: build-debian:11
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --disable-gcc --prefix=/INSTALL
    - make -j8 install


7.3.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:9
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=7.3.0 --prefix=/INSTALL
    - make -j8 install
    - make check


7.4.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:9
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=7.4.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check


7.5.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:9
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=7.5.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check


8.1.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:9
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=8.1.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check

8.2.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:9
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=8.2.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check

8.3.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:9
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=8.3.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check

8.4.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:9
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=8.4.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check

9.1.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:9
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=9.1.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check


9.2.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:9
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=9.2.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check


9.3.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:9
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=9.3.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check

10.1.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:11
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=10.1.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check


10.2.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:11
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=10.2.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check

10.3.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:11
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=10.3.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check

11.1.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:11
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=11.1.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check


11.2.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:11
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=11.2.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check


11.3.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:11
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=11.3.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check

12.1.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:11
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=12.1.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check

12.2.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:11
  script:
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=12.2.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check

12.3.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:11
  script:
    - apt-get update -y && apt-get install texinfo -y
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=12.3.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check

12.4.0:
  stage: Validation
  tags:
    - docker
  image: build-debian:11
  script:
    - apt-get update -y && apt-get install texinfo -y
    - pwd
    - ls
    - mkdir /BUILD
    - cd /BUILD
    - ${CI_PROJECT_DIR}/configure --gcc-version=12.4.0 --prefix=/INSTALL --disable-workshare
    - make -j8 install
    - make check

